version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /c/Users/0633/Desktop/mysql_data
      o: bind
